### ISSUE TITLE
Console.log/error support

### ISSUE THREAD

**Issue by DarkAxi0m** [substack/node-charm#32]
We have an existing project, that heavily uses console.log and .error messages; is there a way to still show these message underneath the charm output?

**Comment by noffle** [comment]
Your best bet for keeping a legacy codebase working might be to override
the console.log and console.error functions to perform charm operations
of their own: manually moving the cursor elsewhere before printing.

You might also get some mileage from text-layers:
https://github.com/substack/text-layers

**Comment by DarkAxi0m** [comment]
That was my feeling; just thought I would ask.

Thank's for the text-layers hint, that might just do what we need.
