### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by zixia** [substack/node-charm#34]
### Reproduce

test.js:

```js
var charm = require('charm');

for (let i = 0; i < 15; i++ ){
  charm()
}
```

```shell
$ node t.js 
(node:26953) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ^C listeners added. Use emitter.setMaxListeners() to increase limit
(node:26953) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by noffle** [comment]
Does this mean there's a memory leak? You've created 15 instances of `charm`, so it makes sense that there are > 11 listeners alive.

**Comment by zixia** [comment]
In short: yes, it does because this behavior will cause problems when we need to reuse the charm.

Long description:

I'm developing a CLI using `blessed-contrib`, start from this example: https://github.com/yaronn/blessed-contrib/blob/master/examples/picture.js

If we only display one picture, it's ok. However, I need to do a slide show, which means I need to call `setImage()` from https://github.com/chjj/blessed#ansiimage-from-box

When we call `setImage()` multiple times, the MaxListeners warning will appear. After hundreds of times, the system will be extremely slow because of too many listeners.

I dive into the code, found that it is because the `blessed-contrib` requires `picture-tube`, and the `picture-tube` requires `charm` and call `charm()` everytime it generate a new picture.

**Comment by noffle** [comment]
I wonder if the easier venue would be to patch `picture-tube` to not recreate charm every time it's used.

Otherwise, we could add a `close()` function to charm that unhooks all of the stdin/stdout pipes and listeners. Still, picture-tube would need patching to use that `close()` function.

**Comment by zixia** [comment]
Yes, under the current behavior of `charm`, the other library needs to be patched.

However, I'm wondering why the new instance will remain the old listeners, could we just create a totally new instance, and let the old instance be garbage collected?

BTW: I finally used this work around to close all the old listeners:

```js
    const c = charm()
    c.removeAllListeners('close')
    c.removeAllListeners('data')
    c.removeAllListeners('end')
    c.removeAllListeners('^C')

    await setImage(image, faceFileList[i])
```

**Comment by noffle** [comment]
Interesting! I hadn't really thought about how eventemitters get garbage collected.

Bummer: I'm not able to reproduce the listeners messages on node `6.9.5`. Nor can I reproduce a memory leak. I ran

```js
var charm = require('.');

var i = 0
function foo () {
  var c = charm()
  console.log(i++)
  process.nextTick(foo)
}
foo()
```
I was surprised to see that even after 4.5 million instances of `charm` my memory use wasn't going up. Garbage collection seems to be working: memuse would go up a bit and then hop back down on `top`.

When you run the above do you see your system memory fill up?

**Comment by zixia** [comment]
1. I ran the code, the listener message could be reproduced.

I guess you missed the message because the output is too fast.

I change the code as the following to make it clear:
```js
var charm = require('charm');

var i = 0
function foo () {
  var c = charm()
  console.log(i++)
  if (i < 15) {
    process.nextTick(foo)
  }
}
foo()
```

The output is:

```shell
$ node --version
v8.4.0

$ node t.js 
0
1
2
3
4
5
6
7
8
9
10
(node:18787) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ^C listeners added. Use emitter.setMaxListeners() to increase limit
(node:18787) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
11
12
13
14
```

2. About the memory usage, I guess it is not going up because the code only adds listeners without doing anything.

As my experience, when we use charm to do some operations, as the listeners more and more, then the performance will get worse and at last, could not work anymore.

**Comment by noffle** [comment]
Even without the `console.log` output there are no messages from node. I don't deny your experience, but I'm not able to reproduce it. What version of node and OS?

**Comment by noffle** [comment]
Also, I'm happy to accept patches to `charm` that fix the memleak or add a `close` method or whatever you need. :+1:

**Comment by zixia** [comment]
I can reproduce it on my Mac Pro and Ubuntu 17.04:

```shell
┌ zixia@zixia-desktop:~/git/node-facenet [01:26:19] tty:[1] jobs:[0]
└ {master} $ uname -r
4.10.0-32-generic
┌ zixia@zixia-desktop:~/git/node-facenet [01:26:20] tty:[1] jobs:[0]
└ {master} $ node --version
v8.4.0
┌ zixia@zixia-desktop:~/git/node-facenet [01:26:22] tty:[1] jobs:[0]
└ {master} $ node t.js 
0
1
2
3
4
5
6
7
8
9
10
(node:14164) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ^C listeners added. Use emitter.setMaxListeners() to increase limit
(node:14164) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
11
12
13
14
```

Thanks for telling me that you accept patches. I'd like to have a look at it to see if I could fix this problem.

Have a nice day!

**Comment by zixia** [comment]
Today I just found this issue had been already fixed a year ago:
https://github.com/substack/node-charm/commit/30e28ef0acd15597f1d48e10e00391916e7f4c11

However, the picture-tube module is still using the old version:
```
    "charm": "~0.1.0",
```

That's why I ran into this issue.

Anyway, thanks for the great repo!

**Comment by noffle** [comment]
Nice! I poked @substack on IRC re your PR on picture-tube. Glad you managed to figure it out.

**Comment by zixia** [comment]
Awesome, thanks!
